In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create and Read

#### 1D Array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(6,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

6

#### 2D Array

In [10]:
arr2 = np.array([[1, 2, 3], [6, 5, 4]])
arr2

array([[1, 2, 3],
       [6, 5, 4]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.size

6

#### 3D Array

In [15]:
arr3 = np.array([[[1, 2, 3], [6, 5, 4]], [[1, 2, 3], [6, 5, 4]], [[1, 2, 3], [6, 5, 4]]])
arr3

array([[[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]]])

In [16]:
arr3.ndim

3

In [17]:
arr3.shape

(3, 2, 3)

In [18]:
arr3.size

18

### Create Random Array

In [19]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.33003014, 0.0699719 , 0.23984151],
        [0.34675019, 0.01320494, 0.40221799]],

       [[0.42812792, 0.96756211, 0.93967423],
        [0.02450604, 0.56231756, 0.99638821]],

       [[0.8768972 , 0.32352854, 0.27918235],
        [0.66213144, 0.26567467, 0.53098705]]])

In [20]:
randomArr.dtype

dtype('float64')

In [21]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
zeroes.ndim

3

In [23]:
full = np.full((3, 2, 3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [24]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
arr3

array([[[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]]])

In [31]:
arr3[0]

array([[1, 2, 3],
       [6, 5, 4]])

In [27]:
arr3[0:2]

array([[[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]]])

In [32]:
arr3[-1]

array([[1, 2, 3],
       [6, 5, 4]])

In [33]:
arr3[1][0][1]

np.int64(2)

In [36]:
arr3[1, 0, 1]

np.int64(2)

### Update and Delete

In [37]:
a1 = np.random.rand(2,3, 2)
a2 = np.random.rand(2,3, 2)

In [38]:
a1

array([[[0.68817304, 0.07369566],
        [0.96266272, 0.2462242 ],
        [0.51435032, 0.54489644]],

       [[0.95962951, 0.01287343],
        [0.50912451, 0.8973205 ],
        [0.36522537, 0.60906038]]])

In [39]:
a2

array([[[0.53419855, 0.63622078],
        [0.05624143, 0.19799576],
        [0.73698102, 0.88752213]],

       [[0.42086846, 0.28306722],
        [0.94863432, 0.51954183],
        [0.2632992 , 0.64022422]]])

#### Basic Math Operations

In [40]:
np.add(a1, a2)

array([[[1.22237159, 0.70991644],
        [1.01890415, 0.44421997],
        [1.25133134, 1.43241857]],

       [[1.38049797, 0.29594065],
        [1.45775882, 1.41686233],
        [0.62852457, 1.2492846 ]]])

In [41]:
np.subtract(a1, a2)

array([[[ 0.15397449, -0.56252513],
        [ 0.90642129,  0.04822844],
        [-0.22263071, -0.34262569]],

       [[ 0.53876105, -0.27019378],
        [-0.43950981,  0.37777867],
        [ 0.10192617, -0.03116384]]])

In [42]:
np.divide(a1, a2)

array([[[ 1.28823457,  0.11583346],
        [17.1166118 ,  1.2435832 ],
        [ 0.69791528,  0.61395251]],

       [[ 2.28011744,  0.04547837],
        [ 0.53669206,  1.72713813],
        [ 1.38711158,  0.95132356]]])

In [43]:
np.multiply(a1, a2)

array([[[0.36762104, 0.04688671],
        [0.05414153, 0.04875135],
        [0.37906642, 0.48360765]],

       [[0.4038778 , 0.00364405],
        [0.48297298, 0.46619553],
        [0.09616355, 0.38993521]]])

### Statistical Operations

In [44]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [45]:
sqrt

np.float64(5.0)

In [46]:
abs

np.int64(2)

In [47]:
power

np.int64(256)

In [48]:
log

np.float64(3.2188758248682006)

In [49]:
mins

np.float64(0.012873434956466423)

In [50]:
maxs

np.float64(0.9486343179284192)

### Update

In [51]:
arr3

array([[[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]],

       [[1, 2, 3],
        [6, 5, 4]]])

In [52]:
arr3[0,0,2] = 500
arr3

array([[[  1,   2, 500],
        [  6,   5,   4]],

       [[  1,   2,   3],
        [  6,   5,   4]],

       [[  1,   2,   3],
        [  6,   5,   4]]])

In [53]:
arr3.sort()
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[  1,   2,   3],
        [  4,   5,   6]]])

In [54]:
# Reshape
arr3.shape

(3, 2, 3)

In [55]:
arr3_reshape = arr3.reshape((2, 3, -1))
arr3_reshape

array([[[  1,   2, 500],
        [  4,   5,   6],
        [  1,   2,   3]],

       [[  4,   5,   6],
        [  1,   2,   3],
        [  4,   5,   6]]])

In [56]:
arr3_reshape.shape

(2, 3, 3)

### Appending & Inserting

In [57]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
#Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
appd = np.append(zeroes, new_array, axis=0) # axis = 0 row, axis = 1 col
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [60]:
# Insert

In [61]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [62]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [63]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [64]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.86947985, 0.89961676, 0.64706874],
        [0.80195157, 0.31982946, 0.34761712]],

       [[0.88008998, 0.59063962, 0.05397871],
        [0.44957929, 0.37159594, 0.34647549]],

       [[0.22505686, 0.382578  , 0.26781985],
        [0.17276524, 0.14687751, 0.55600902]]])

In [65]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [66]:
arr5

array([[[0.80195157, 0.31982946, 0.34761712]],

       [[0.44957929, 0.37159594, 0.34647549]],

       [[0.17276524, 0.14687751, 0.55600902]]])

In [67]:
np.save("new_array", arr5)

In [68]:
np.load("new_array.npy")

array([[[0.80195157, 0.31982946, 0.34761712]],

       [[0.44957929, 0.37159594, 0.34647549]],

       [[0.17276524, 0.14687751, 0.55600902]]])